name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        severity: warning
        check_together: 'yes'
        format: gcc
        
  test:
    name: Test Installation
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y jq bc
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install jq bc
        fi
        
    - name: Test statusline scripts
      run: |
        chmod +x *.sh
        echo '{"model":{"display_name":"Test"},"workspace":{"current_dir":"'$PWD'"}}' | ./statusline-basic.sh
        echo '{"model":{"display_name":"Test"},"workspace":{"current_dir":"'$PWD'"}}' | ./statusline-minimal.sh
        echo '{"model":{"display_name":"Test"},"workspace":{"current_dir":"'$PWD'"}}' | ./statusline-segments.sh
        
    - name: Test manager script
      run: |
        ./statusline-manager.sh --help
        
    - name: Test installation script
      run: |
        NO_COLOR=1 ./install.sh --help
        
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'